<?php

namespace Services\Zoo\Service;

// Class imports

// Namespace imports
use Services\Zoo\Thrift;
use Services\Zoo\Exception;

/**
 * @package Services\Zoo
 *
 * Generated by com.upwork.donkey.example.php.GeneratorAwareTemplateGroupFactory vdonkey-example:1.0-SNAPSHOT
 */
interface StaffService
{
    /**
     *
     * @param Thrift\Person|null $janitor
     */
    public function hireJanitor(?Thrift\Person $janitor): void;

    /**
     *
     * @param Thrift\Person|null $guard
     */
    public function hireGuard(?Thrift\Person $guard): void;

    /**
     * Find employees by their first name or last name
     *
     * @param string|null $firstName
     * @param string|null $lastName
     *
     * @return Thrift\PersonList|null
     */
    public function getAllEmployees(?string $firstName, ?string $lastName): ?Thrift\PersonList;

    /**
     * Fire an employee by their ID number
     *
     * @param string $id
     */
    public function terminateEmployee(string $id): void;
}