/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.example.services.zoo.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-04-27")
public class PersonList implements org.apache.thrift.TBase<PersonList, PersonList._Fields>, java.io.Serializable, Cloneable, Comparable<PersonList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PersonList");

  private static final org.apache.thrift.protocol.TField PERSONS_FIELD_DESC = new org.apache.thrift.protocol.TField("persons", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PersonListStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PersonListTupleSchemeFactory();

  public java.util.List<Person> persons; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PERSONS((short)1, "persons");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PERSONS
          return PERSONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PERSONS, new org.apache.thrift.meta_data.FieldMetaData("persons", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Person.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PersonList.class, metaDataMap);
  }

  public PersonList() {
  }

  public PersonList(
    java.util.List<Person> persons)
  {
    this();
    this.persons = persons;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PersonList(PersonList other) {
    if (other.isSetPersons()) {
      java.util.List<Person> __this__persons = new java.util.ArrayList<Person>(other.persons.size());
      for (Person other_element : other.persons) {
        __this__persons.add(new Person(other_element));
      }
      this.persons = __this__persons;
    }
  }

  public PersonList deepCopy() {
    return new PersonList(this);
  }

  @Override
  public void clear() {
    this.persons = null;
  }

  public int getPersonsSize() {
    return (this.persons == null) ? 0 : this.persons.size();
  }

  public java.util.Iterator<Person> getPersonsIterator() {
    return (this.persons == null) ? null : this.persons.iterator();
  }

  public void addToPersons(Person elem) {
    if (this.persons == null) {
      this.persons = new java.util.ArrayList<Person>();
    }
    this.persons.add(elem);
  }

  public java.util.List<Person> getPersons() {
    return this.persons;
  }

  public PersonList setPersons(java.util.List<Person> persons) {
    this.persons = persons;
    return this;
  }

  public void unsetPersons() {
    this.persons = null;
  }

  /** Returns true if field persons is set (has been assigned a value) and false otherwise */
  public boolean isSetPersons() {
    return this.persons != null;
  }

  public void setPersonsIsSet(boolean value) {
    if (!value) {
      this.persons = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PERSONS:
      if (value == null) {
        unsetPersons();
      } else {
        setPersons((java.util.List<Person>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PERSONS:
      return getPersons();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PERSONS:
      return isSetPersons();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof PersonList)
      return this.equals((PersonList)that);
    return false;
  }

  public boolean equals(PersonList that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_persons = true && this.isSetPersons();
    boolean that_present_persons = true && that.isSetPersons();
    if (this_present_persons || that_present_persons) {
      if (!(this_present_persons && that_present_persons))
        return false;
      if (!this.persons.equals(that.persons))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPersons()) ? 131071 : 524287);
    if (isSetPersons())
      hashCode = hashCode * 8191 + persons.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(PersonList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPersons()).compareTo(other.isSetPersons());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPersons()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.persons, other.persons);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PersonList(");
    boolean first = true;

    sb.append("persons:");
    if (this.persons == null) {
      sb.append("null");
    } else {
      sb.append(this.persons);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PersonListStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PersonListStandardScheme getScheme() {
      return new PersonListStandardScheme();
    }
  }

  private static class PersonListStandardScheme extends org.apache.thrift.scheme.StandardScheme<PersonList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PersonList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PERSONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.persons = new java.util.ArrayList<Person>(_list0.size);
                Person _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new Person();
                  _elem1.read(iprot);
                  struct.persons.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setPersonsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PersonList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.persons != null) {
        oprot.writeFieldBegin(PERSONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.persons.size()));
          for (Person _iter3 : struct.persons)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PersonListTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PersonListTupleScheme getScheme() {
      return new PersonListTupleScheme();
    }
  }

  private static class PersonListTupleScheme extends org.apache.thrift.scheme.TupleScheme<PersonList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PersonList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPersons()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPersons()) {
        {
          oprot.writeI32(struct.persons.size());
          for (Person _iter4 : struct.persons)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PersonList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.persons = new java.util.ArrayList<Person>(_list5.size);
          Person _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new Person();
            _elem6.read(iprot);
            struct.persons.add(_elem6);
          }
        }
        struct.setPersonsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

