<?php

namespace Services\Zoo\Exception;

/**
 * @package Services\Zoo\Exception
 *
 * Generated by com.upwork.donkey.example.php.GeneratorAwareTemplateGroupFactory vdonkey-example:1.0-SNAPSHOT
 */
class InvalidAnimalTypeException extends ZooException
{
    const STATUS_CODE = 400;
    const ERROR_CODE = 1;

    /**
     * @param string|null $message
     * @param \Throwable|null $previous
     */
    public function __construct(?string $message = "", ?\Throwable $previous = null)
    {
        parent::__construct(self::STATUS_CODE, self::ERROR_CODE, $message, $previous);
    }
}